version: "3"
services:
    frontend-app:
        build:
            context: ../frontend-app
            dockerfile: Dockerfile
        command: ["/bin/bash", "-c", "/init.sh"]
        environment:
            - HYDRA_ENV=dev
            - XDEBUG_ENABLED=1
        ports:
            - 80:80
        restart: always
        volumes:
            - "../frontend-app/src:/var/www/html"
